### ISSUE TITLE
使用github action執行

### ISSUE THREAD

**Issue by kevin930321** [Jia35/gamer_fuli_exchange#1]
不好意思，我試著用 github action 來執行這個程式，這是我的 .yml :

    name: 每天的自動化
    
    on:
      schedule:
        - cron: '30 4 * * *'
    
      workflow_dispatch:
    
    jobs:
        automation:
            name: 自動化
            runs-on: ubuntu-latest
            steps:
                - name: Checkout Repository
                  uses: actions/checkout@v4
                
                - name: Install dependencies
                  run: |
                    pip install --upgrade pip
                    pip install -r requirements.txt (bs4,requests,beautifulsoup4,configparser,playwright)
    
                - name: Build Environment
                  run: | 
                    playwright install
    
                - name: Run Python scripts
                  run: |
                    python main.py -c "save_cookie()"
                    python main.py -c "exchange_all_goods(is_crawl=True)"

但它都只跑出 :

    python main.py -c "save_cookie()"
    python main.py -c "exchange_all_goods(is_crawl=True)"
    shell: /usr/bin/bash -e {0}

請問你知道這要怎麼解決嗎? 謝謝。

**Comment by Jia35** [comment]
不好意思，我沒用過 github action，可能沒辦法幫你
(如果只讓他跑 python main.py 可以嗎？)

但這個自動觀看廣告的程式，我記得很久之前我試已經不行了...
(我甚至忘記我有寫這個😂)
